// @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}


###
@authToken = {{auth.response.body.access_token}}

###
DELETE http://localhost:7000/api/development-knowledges/
Authorization: Bearer {{authToken}}

###
POST http://localhost:7000/api/development-knowledges/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "technology" : "C#",
  "usedInProject": true,
  "followedTraining": true,
  "usedInLastYear": true,
  "usedInPersonalProject": true,
  "level": 5
}

###
POST http://localhost:7000/api/development-knowledges/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "technology" : "Node.JS (Express)",
  "usedInProject": false,
  "followedTraining": true,
  "usedInLastYear": true,
  "usedInPersonalProject": true,
  "level": 2
}

###
POST http://localhost:7000/api/development-knowledges/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "technology" : "CSS / SASS",
  "usedInProject": true,
  "followedTraining": true,
  "usedInLastYear": true,
  "usedInPersonalProject": true,
  "level": 3
}