POST http://localhost:7000/api/keywords/
content-type: application/json

{
  "keyWord": "Full stack developer",
  "translations": [
    { "language": "nl", "translation": "Full stack developer"},
    { "language": "fr", "translation": "Full stack développeur"}
  ]
}