POST http://localhost:7000/content/
content-type: application/json

{
  "container": "header",
  "key": "intro",
  "value": "Welcome to CV of Servaas Phlips",
  "translations": [
    { "language": "nl", "translation": "Welkom op de CV van Servaas Phlips"},
    { "language": "fr", "translation": "Bienvenue à CV de Servaas Phlips"}
  ]
}