// @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}


###
@authToken = {{auth.response.body.access_token}}
###
DELETE http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "nl",
  "year" : 2018,
  "type": "conference",
  "description": "JS Conf 2018 : architecture of SPAs, CSS with Houdini, PWA, Nativescript, new developments in Javascripts"
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "nl",
  "year" : 2022,
  "type": "training",
  "description": "Full Stack open 2022 : deep-dive training on React, Express, Redux and GraphQL"
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "nl",
  "year" : 2022,
  "type": "home-project",
  "description": "Online C.V. met gebruik van React, Express, Redux, Sass, MongoDB and Azure cloud"
}


###
GET http://localhost:7000/api/update-knowledges/