// @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}


###
@authToken = {{auth.response.body.access_token}}
###
DELETE http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2018,
  "type": "conference",
  "description": "JS Conf 2018 : architecture of SPAs, CSS with Houdini, PWA, Nativescript, new developments in Javascripts"
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2019,
  "type": "conference",
  "description": "JS Conf 2019 : React Apps, Password are so 1990, Search for appiness PWA, ..."
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2019,
  "type": "conference",
  "description": "Techorama 2019 : state of C#, Enterprise GRADe Web Apis, healt checks in .Net core, Design Patterns"
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2022,
  "type": "training",
  "description": "Full Stack open 2022 : React, Express, Redux and GraphQL"
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2022,
  "type": "home-project",
  "description": "Online C.V. using React, Express, Redux, Sass, MongoDB and Azure cloud"
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2017,
  "type": "certification",
  "description": "Sitecore 8 certified developer"
}


###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2021,
  "type": "home-project",
  "description": "Orderprocessor in C# and .Net core with Azure functions to integrate between a REST shop and APIs of resellers."
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2018,
  "type": "home-project",
  "description": "React website in javascript to monitor crypto-assets. Integration with REST crypto web service and Firebase."
}

###
POST http://localhost:7000/api/update-knowledges/
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "languageCode" : "en",
  "year" : 2020,
  "type": "training",
  "description": "Angular - The Complete Guide op Udemy"
}



###
GET http://localhost:7000/api/update-knowledges/