// @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}
###
@authToken = {{auth.response.body.access_token}}

###
DELETE http://localhost:7000/api/work-experiences/
Authorization: Bearer {{authToken}}

### 
POST http://localhost:7000/api/work-experiences/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "languageCode": "nl",
  "startDate": "2020-12-15",
  "description": "working on stuff",
  "projects": [
      {
        "description" : "do some stuff",
        "tasks" : ["one thing", "another thing"]
      }
  ],
  "keywords" : ["C++", "Cobol"]

}

### 
GET  http://localhost:7000/api/work-experiences/nl